---
title: "Analysis"
author: "Pedro Girardi"
date: "January 27, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(tidyverse)
library(data.table)
library(lme4)
```

## Importing df

```{r}
complete.df = fread("complete.csv")
```

## Recoding Variables

Variables:

v203: Gender (Male=1)
v208: Ethnicity (White=1, Black=2, Yellow=3, Mixed=4, Native=5, Ignored=9)
v4191: Income (999999999 = ignored)
v301: Writes/reads? (Yes=1, No=2, 0="Deleted by the surveyer", NA=NA)
v307: schooling (a mess...)/turn into factor
v234: age

ADD 409 (TYPE OF WORKER!!!!)

```{r}
complete.df = complete.df %>% mutate(Gender = as.factor(v203),
                       Ethnicity = as.factor(v208),
                       Literacy = as.factor(v301),
                       Schooling = as.factor(v307)) %>% 
                              select(-v040, -v050, -v203, -v208, -v301, -v307,
                                     -starts_with("vD"), -p201)
complete.df$Schooling = as.factor(ifelse(is.na(complete.df$Schooling), "NoSchooling", complete.df$Schooling))
levels(complete.df$Gender) = c("Male", "Female")
levels(complete.df$Ethnicity) = c("White", "Black", "Yellow", "Mixed", "Native", "Ignored")
levels(complete.df$Literacy) = c("Yes", "No")
levels(complete.df$Schooling) = c("Primary", "HighSchool_1", "HighSchool_2",
                                  "MiddleSchool", "HighSchool_3", "College",
                                  "AdultsSchool", "PreSchool", "Graduate",
                                  "NoSchooling")
```

## Visually checking for mixed effects

```{r}
set.seed(2)
ggplot(complete.df %>% filter(idind %in% sample(complete.df$idind, size = 25)),
       aes(x=lagInflationTax, y=realWage)) +
  geom_point(aes(col=idind)) +
  geom_smooth(aes(col=idind), method = "lm", se = F) +
  theme_minimal() +
  theme(legend.position="none")
```

## Fitting LME model

```{r Testing random slopes}
lmer1 <- lmer(log(realWage) ~ v035 + lagInflationTax + ChangeInGDP +
                (Gender + Ethnicity + Literacy + Schooling)*lagInflationTax+
                (lagInflation | idind), data = complete.df)
summary(lmer1)

lmer2 = lmer(log(realWage) ~ v035 + lagInflationTax + ChangeInGDP +
                (Gender + Ethnicity + Literacy + Schooling)*lagInflationTax+
               (1 | idind), data = complete.df)
summary(lmer2)

deviance_lme = 2*(logLik(lmer1)-logLik(lmer2))
.5*(1-pchisq(deviance_lme, 2)) + .5*(1-pchisq(deviance_lme, 1)) #pvalue of 0 indicates you need the random slope! 
AIC(lmer1)
AIC(lmer2)
# needs random slopes, which means that people are impacted differently by inflation
```

```{r Working with fixed effects}
lmer1_fe = update(lmer1, REML=F)
lmer3_fe = update(lmer1_fe, . ~ . -lagInflationTax:Ethnicity -lagInflationTax:Literacy -lagInflationTax:Gender)
summary(lmer1_fe)
summary(lmer3_fe)
D <- 2*(logLik(lmer1_fe)-logLik(lmer3_fe))
1-pchisq(D, (length(summary(lmer1_fe)$coefficients[,1]))-length(summary(lmer3_fe)$coefficients[,1]))[[1]]
# shorter model is appropriate
```

```{r}
# to-do: add variable type of work, run analysis with full dataset and check for significance, test diagnostics/assumptions 
```



